import Head from "next/head";

import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-3">
          <h1 className="text-gray-800 font-bold text-3xl my-6 mx-4">
            {`Research.
            Reach.
            Realize.
            Properties ™
          `}
          </h1>
          <p className="text-custom-gray font-roboto text-base font-normal md:mb-[40px] mb-[23px] mx-4">
            Kanvas is a real estate technology platform that simplifies the
            process of buying and selling residential properties.
          </p>
          <p className="text-custom-gray font-roboto text-base font-normal md:mb-[40px] mb-[23px] mx-4">
            Our mission is to provide an efficient and transparent real estate
            experience for everyone.
          </p>

          <form>
            <label htmlFor="mail">
              Redefine real estate, join the waitlist:
            </label>
            <input
              id="mail"
              name="email"
              type="email"
              placeholder="Enter your email"
              required
            />
          </form>

          <a href="tel:+1855526827">+1-855-KANVAS</a>

          <p>© 2024 Kanvas.co</p>

          <Image src="/image.png" alt="" width={100} height={100} />
        </div>
      </main>
    </>
  );
}
